#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("StartWorkplace.Resource", IsApplication=true)]

namespace StartWorkplace
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::KeeperData.Resource.String.library_name = global::StartWorkplace.Resource.String.library_name;
			global::VectorDataLayer.Resource.String.library_name = global::StartWorkplace.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int my_cellback = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int my_green = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CustomSelector1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int del = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07002a
			public const int btnAddWinch = 2131165226;
			
			// aapt resource value: 0x7f07001c
			public const int btnCancelWinchCommand = 2131165212;
			
			// aapt resource value: 0x7f07002b
			public const int btnDelWinch = 2131165227;
			
			// aapt resource value: 0x7f070009
			public const int btnSelectKonchinka = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int btnSelectNovoe = 2131165188;
			
			// aapt resource value: 0x7f07001b
			public const int btnSelectWinchCommand = 2131165211;
			
			// aapt resource value: 0x7f07002e
			public const int btnStarterAdd = 2131165230;
			
			// aapt resource value: 0x7f070015
			public const int btnStarterCancel = 2131165205;
			
			// aapt resource value: 0x7f07002f
			public const int btnStarterDel = 2131165231;
			
			// aapt resource value: 0x7f070014
			public const int btnStarterMemberAdd = 2131165204;
			
			// aapt resource value: 0x7f070025
			public const int editFreq = 2131165221;
			
			// aapt resource value: 0x7f070003
			public const int frameLayout1 = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int frameLayout2 = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int frameLayout3 = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int frameLayout4 = 2131165194;
			
			// aapt resource value: 0x7f070031
			public const int layStandardList = 2131165233;
			
			// aapt resource value: 0x7f070026
			public const int layoutFlightDir = 2131165222;
			
			// aapt resource value: 0x7f070030
			public const int layoutFooter = 2131165232;
			
			// aapt resource value: 0x7f070021
			public const int layoutHeader = 2131165217;
			
			// aapt resource value: 0x7f070007
			public const int layoutKonchinka = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int layoutMain = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int layoutNovoe = 2131165186;
			
			// aapt resource value: 0x7f07002c
			public const int layoutStart = 2131165228;
			
			// aapt resource value: 0x7f070028
			public const int layoutWinch = 2131165224;
			
			// aapt resource value: 0x7f07000d
			public const int linearLayout1 = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int linearLayout2 = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int linearLayout3 = 2131165203;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout4 = 2131165196;
			
			// aapt resource value: 0x7f07002d
			public const int lvStartCommand = 2131165229;
			
			// aapt resource value: 0x7f070029
			public const int lvWinchTeam = 2131165225;
			
			// aapt resource value: 0x7f07000f
			public const int spnAddStarterEmploee = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int spnAddStarterPos = 2131165202;
			
			// aapt resource value: 0x7f070027
			public const int spnFlightDir = 2131165223;
			
			// aapt resource value: 0x7f070017
			public const int spnSelectWinch = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int spnSelectWinchAssistant = 2131165210;
			
			// aapt resource value: 0x7f070018
			public const int spnSelectWinchOperator = 2131165208;
			
			// aapt resource value: 0x7f070023
			public const int textData = 2131165219;
			
			// aapt resource value: 0x7f07001d
			public const int textError = 2131165213;
			
			// aapt resource value: 0x7f070016
			public const int textErrorAddStarter = 2131165206;
			
			// aapt resource value: 0x7f070001
			public const int textFilghts = 2131165185;
			
			// aapt resource value: 0x7f070024
			public const int textFreq = 2131165220;
			
			// aapt resource value: 0x7f07000b
			public const int textKonchinka = 2131165195;
			
			// aapt resource value: 0x7f07001e
			public const int textListRow = 2131165214;
			
			// aapt resource value: 0x7f070006
			public const int textNovoe = 2131165190;
			
			// aapt resource value: 0x7f070022
			public const int textParadrom = 2131165218;
			
			// aapt resource value: 0x7f07001f
			public const int textStarterEmploee = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int textStarterPosition = 2131165216;
			
			// aapt resource value: 0x7f07000e
			public const int textView1 = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int textView2 = 2131165201;
			
			// aapt resource value: 0x7f070019
			public const int textView3 = 2131165209;
			
			// aapt resource value: 0x7f070033
			public const int textWinchEmploee = 2131165235;
			
			// aapt resource value: 0x7f070032
			public const int textWinchName = 2131165234;
			
			// aapt resource value: 0x7f070034
			public const int textWinchPosition = 2131165236;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SelectStarterWorker = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int SelectWinchCommand = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int SimpleListRow = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int StartCommandTableRow = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int StartDay = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int WinchTeamRow = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_add = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Icon = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
